# Generated by Django 4.2.11 on 2024-05-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
