# Generated by Django 4.2.11 on 2024-05-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_opinion_calification'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='link_image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
