# Generated by Django 4.2.11 on 2024-05-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_usuario_email_alter_usuario_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
